const Screens = {
    BOOKAPPOINTMENT: 'BOOKAPPOINTMENT',
    BOOKINGFINALIZED: 'BOOKINGFINALIZED',
    BOOKINGSUCCESSFULLY: 'BOOKINGSUCCESSFULLY',
    CHILDSERVICES: 'CHILDSERVICES',



};

export default Screens;