const Screens = {
    BOOKAPPOINTMENT: 'BOOKAPPOINTMENT',
    BOOKINGFINALIZED: 'BOOKINGFINALIZED',
    BOOKINGSUCCESSFULLY: 'BOOKINGSUCCESSFULLY',
    CHILDSERVICES: 'CHILDSERVICES',
    PROFILE :'PROFILE',
    CART :'CART'



};

export default Screens;